# Generated by Django 5.0.6 on 2024-07-27 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('home', 'Home'), ('about', 'About'), ('service', 'Service'), ('blog', 'Blog'), ('contact_us', 'Contact Us')], max_length=20)),
                ('title', models.CharField(max_length=60)),
                ('meta_title', models.CharField(max_length=60)),
                ('meta_description', models.CharField(max_length=180)),
                ('url', models.URLField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='meta_image/')),
            ],
            options={
                'verbose_name': 'Meta',
                'verbose_name_plural': 'Metas',
                'ordering': ('-id',),
            },
        ),
    ]
