# Generated by Django 5.0.1 on 2024-12-03 17:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0004_meta"),
    ]

    operations = [
        migrations.RenameField(
            model_name="meta",
            old_name="url",
            new_name="canonical_url",
        ),
        migrations.RemoveField(
            model_name="meta",
            name="title",
        ),
        migrations.AlterField(
            model_name="meta",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="meta_image/"),
        ),
    ]
