# Generated by Django 5.0.1 on 2024-12-03 17:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0005_rename_url_meta_canonical_url_remove_meta_title_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="meta",
            name="meta_keyword",
            field=models.CharField(default=1, max_length=180),
            preserve_default=False,
        ),
    ]
