# Generated by Django 5.0.1 on 2024-12-03 18:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0006_meta_meta_keyword"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="service_icon",
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
    ]
