# Generated by Django 5.0.1 on 2024-12-03 19:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0008_alter_service_service_icon"),
    ]

    operations = [
        migrations.AddField(
            model_name="banner",
            name="sub_title",
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
