# Generated by Django 5.0.1 on 2024-12-03 19:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0009_banner_sub_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="banner",
            name="sub_title",
        ),
    ]
