# Generated by Django 5.0.1 on 2024-12-03 19:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0011_alter_banner_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="banner",
            name="title",
            field=models.CharField(max_length=150),
        ),
    ]
