# Generated by Django 5.0.1 on 2024-12-03 19:20

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0012_alter_banner_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="About",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("about_title", models.CharField(max_length=120)),
                ("About_us", tinymce.models.HTMLField()),
                ("Our_Vision", tinymce.models.HTMLField()),
                ("Our_Mission", tinymce.models.HTMLField()),
            ],
            options={
                "verbose_name": "About",
                "verbose_name_plural": "Abouts",
                "ordering": ("-id",),
            },
        ),
    ]
