# Generated by Django 5.0.1 on 2024-12-03 19:22

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0013_about"),
    ]

    operations = [
        migrations.RenameField(
            model_name="about",
            old_name="About_us",
            new_name="about_us",
        ),
        migrations.RenameField(
            model_name="about",
            old_name="Our_Mission",
            new_name="our_mission",
        ),
        migrations.RenameField(
            model_name="about",
            old_name="Our_Vision",
            new_name="our_value",
        ),
        migrations.AddField(
            model_name="about",
            name="our_vision",
            field=tinymce.models.HTMLField(default=1),
            preserve_default=False,
        ),
    ]
