# Generated by Django 5.0.1 on 2024-12-03 19:26

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0014_rename_about_us_about_about_us_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutUs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("description", tinymce.models.HTMLField()),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="about_us/"),
                ),
            ],
            options={
                "verbose_name": "About Us",
                "verbose_name_plural": "About Us",
                "ordering": ("-id",),
            },
        ),
        migrations.RenameField(
            model_name="about",
            old_name="about_title",
            new_name="whychoose_title",
        ),
        migrations.RenameField(
            model_name="about",
            old_name="about_us",
            new_name="whychoose_us",
        ),
    ]
