# Generated by Django 5.0.1 on 2024-12-03 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0015_aboutus_rename_about_title_about_whychoose_title_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                (
                    "about_us",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="web.aboutus"
                    ),
                ),
            ],
            options={
                "verbose_name": "About Point",
                "verbose_name_plural": "About Points",
                "ordering": ("-id",),
            },
        ),
    ]
