# Generated by Django 5.0.1 on 2024-12-03 19:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0016_aboutpoint"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="About",
            new_name="CoreInfo",
        ),
        migrations.AlterModelOptions(
            name="coreinfo",
            options={
                "ordering": ("-id",),
                "verbose_name": "Core Info",
                "verbose_name_plural": "Core Infos",
            },
        ),
    ]
