# Generated by Django 5.0.1 on 2024-12-03 20:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0017_rename_about_coreinfo_alter_coreinfo_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="coreinfo",
            old_name="our_value",
            new_name="core_value",
        ),
    ]
