# Generated by Django 5.0.1 on 2024-12-03 20:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0018_rename_our_value_coreinfo_core_value"),
    ]

    operations = [
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=180)),
                ("content", models.TextField()),
            ],
            options={
                "verbose_name": "FAW",
                "verbose_name_plural": "FAWs",
                "ordering": ("-id",),
            },
        ),
    ]
