# Generated by Django 5.0.1 on 2024-12-03 20:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0019_faq"),
    ]

    operations = [
        migrations.RenameField(
            model_name="faq",
            old_name="content",
            new_name="answer",
        ),
        migrations.RenameField(
            model_name="faq",
            old_name="title",
            new_name="question",
        ),
    ]
